import java.util.List;

public class Constants {
    public static final String ID_FLAG = "ID";
    public static final String INFO_FLAG = "INFO";



    public static final List<String> NAMES = List.of("Luca",
            "Adalynn",
            "Lana",
            "Darian",
            "Darren",
            "Angelina",
            "Antoine",
            "Sullivan",
            "Edith",
            "Moriah",
            "Tiffany",
            "Lillianna",
            "Owen",
            "Judah",
            "Adison",
            "Jamarion",
            "Jaden",
            "Keon",
            "Efrain",
            "Matthias",
            "Hassan",
            "Carter",
            "Rudy",
            "Hudson",
            "Richard",
            "Darnell",
            "Aliza",
            "Maya",
            "Marvin",
            "Cooper",
            "Shayna",
            "Taylor",
            "Kaiden",
            "Mario",
            "Angel",
            "Jan",
            "Victor",
            "Devin",
            "Jakob",
            "Danika",
            "Alexandra",
            "Irvin",
            "Mattie",
            "Aaden",
            "Rebecca",
            "Karla",
            "Jax",
            "Devon",
            "Bethany",
            "Riley",
            "Malik",
            "Rory",
            "Alexia",
            "Kylie",
            "Maria",
            "Marin",
            "Deangelo",
            "Shannon",
            "Kayden",
            "Skylar",
            "Araceli",
            "Yurem",
            "Kole",
            "Adrian",
            "Jovanny",
            "Teagan",
            "Jaxon",
            "Tyler",
            "Douglas",
            "Kate",
            "Amber",
            "Dax",
            "Terrell",
            "Kolten",
            "Milo");
}
